name: call input file
on:
  push:
   workflow_dispatch: null
jobs:
 Target-workflow-file:
  runs-on: self-hosted
  steps:
  - name: execute file
    uses: babu53/merge/.github/actions/input.yaml@master
    with:
      environment: testdemo
