name: call input file
on:
  push:
   branches:
    - master
jobs:
 Target-workflow-file:
  steps:
   uses: https://github.com/babu53/merge/blob/master/.github/workflows/input.yaml@master
   with:
    environment: testdemo
