name: call input file
on:
  push:
   branches:
    - master
jobs:
 Target-workflow-file:
  steps:
  - name: execute file
    uses: babu53/merge/.github/actions/input.yaml@master
    with:
      environment: testdemo
