name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      component:
        description: 'Choose a component to build'
        required: true
        default: 'frontend'
        type: choice
        options:
          - frontend
          - backend
          - infra

jobs:
  build:
    runs-on: AWS
    steps:
      - uses: actions/checkout@v3
      - name: Run based on choice

          if: "${{ github.event.inputs.component }}" = "backend" ]]
          working-directory: backend
          run: echo "Running backend build"
          
