name: manual input workflow file

on:
 push:
   branches:
    - master
jobs:
 runs-on: self-hosted
 Explore-GitHub-actions-file:
   steps:
   - run: echo "this is test file"
 test:
  steps:
  - run: |
     echo " this is test"
