name: Build and Test Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        run: echo "checkout code"

      - name: Set up Node.js
        run: |
         echo "this Node.js setup"

      - name: Install dependencies
        run: echo " this this install depedencies"

      - name: Build
        run: |
         echo " this is build "

  test:
    runs-on: self-hosted
    # needs: build  # This makes the test job run AFTER build
    steps:
      - name: Checkout code
        run: echo "this is checkout code for build"

      - name: Set up Node.js
        run: |
         echo " this is node js"
         echo " this is apple name is : ${{vars.my}}"

      - name: Install dependencies
        run: |
         echo " this is install dependeccies...."
         echo "this is secret ${{secrets.name}}"
