name: manual input workflow file

on:
 push:
   branches:
    - master
jobs:
 Explore-GitHub-actions-file:
  runs-on: self-hosted
  steps:
    - run: echo "this is test file"
 test:
  steps:
   - run: echo " this is test file"